environment:
    matrix:
        - RUST_INSTALL_TRIPLE: i686-pc-windows-gnu
          RUST_CHANNEL: stable
        - RUST_INSTALL_TRIPLE: x86_64-pc-windows-gnu
          RUST_CHANNEL: stable
        - RUST_INSTALL_TRIPLE: x86_64-pc-windows-msvc
          RUST_CHANNEL: nightly

install:
    - ps: Start-FileDownload "http://static.rust-lang.org/dist/channel-rust-${env:RUST_CHANNEL}"
    - ps: $env:RUST_INSTALLER = Select-String "${env:RUST_INSTALL_TRIPLE}.*exe" "channel-rust-${env:RUST_CHANNEL}" | select -exp line
    - ps: Start-FileDownload "http://static.rust-lang.org/dist/${env:RUST_INSTALLER}"
    - '%RUST_INSTALLER% /VERYSILENT /NORESTART /DIR="C:\Rust"'
    - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
    - ps: ls 'C:\Rust\bin\rustlib\*\bin\*'
    - ps: |
        if (($env:RUST_INSTALL_TRIPLE -like "x86_64*gnu") -And -Not (Test-Path "C:\mingw64")) {
            # Install MinGW.
            $url  = "http://sourceforge.net/projects/mingw-w64/files/"
            $url += "Toolchains%20targetting%20Win64/Personal%20Builds/"
            $url += "mingw-builds/4.9.2/threads-win32/seh/"
            $url += "x86_64-4.9.2-release-win32-seh-rt_v3-rev0.7z/download"
            Invoke-WebRequest -UserAgent wget -Uri $url -OutFile x86_64-4.9.2-release-win32-seh-rt_v3-rev0.7z
            &7z x -oC:\ x86_64-4.9.2-release-win32-seh-rt_v3-rev0.7z > $null
        }
    - set PATH=C:\MinGW64\bin;C:\mingw\bin;%PATH%
    - set PATH=C:\Rust\bin;%PATH%
    - rustc --version
    - cargo --version

build: false

test_script:
    - cargo test
